// AUTO-GENERATED by scripts/generate-blog-manifest.js — do not edit by hand.
// Rerun `node scripts/generate-blog-manifest.js` after adding/removing a blog.
window.BLOG_MANIFEST = [
  "BLOG_discord-s-beginning-of-an-end",
  "BLOG_markdown-editor-tutorial",
  "BLOG_my-2025-tech-journey",
  "BLOG_welcome-to-kuroma-dev"
];
